name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Verify the release version"
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: true
          PACKAGE_DIR: ${{ github.workspace }}/custom_components/cloud_ru_ai
          PACKAGE_NAME: manifest.json
      - name: "Compress"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/cloud_ru_ai"
          zip -r "${{ runner.temp }}/cloud_ru_ai.zip" ./
      - name: "Publish"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ runner.temp }}/cloud_ru_ai.zip
          body: >
            [![Количество скачиваний](https://img.shields.io/github/downloads/black-roland/homeassistant-cloud-ru-ai/${{ github.ref_name }}/total?style=flat-square)](https://github.com/black-roland/homeassistant-cloud-ru-ai/releases)
            [![Донат на кофе](https://img.shields.io/badge/%D0%B4%D0%BE%D0%BD%D0%B0%D1%82-%D0%BD%D0%B0%20%D0%BA%D0%BE%D1%84%D0%B5-cc3336?style=flat-square&logo=coffeescript)](https://mansmarthome.info/donate/#donationalerts)
          generate_release_notes: true
